/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ReviewPolicyRouteImport } from './routes/review-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as StaffInviteTokenRouteImport } from './routes/staff-invite.$token'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HelpSlugRouteImport } from './routes/help.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as ApiTwilioSmsWebhookRouteImport } from './routes/api.twilio-sms-webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiStockScanRouteImport } from './routes/api/stock-scan'
import { Route as ApiResendWebhookRouteImport } from './routes/api.resend-webhook'
import { Route as ApiPublicReviewsRouteImport } from './routes/api/public-reviews'
import { Route as ApiPublicGalleryRouteImport } from './routes/api/public-gallery'
import { Route as ApiPublicBookingStaffRouteImport } from './routes/api/public-booking-staff'
import { Route as ApiPageAiSuggestRouteImport } from './routes/api/page-ai-suggest'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiClientErrorsRouteImport } from './routes/api/client-errors'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfessionalsRouteImport } from './routes/_authenticated/professionals'
import { Route as AuthenticatedPreviewRouteImport } from './routes/_authenticated/preview'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPageBuilderRouteImport } from './routes/_authenticated/page-builder'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedConsultationsRouteImport } from './routes/_authenticated/consultations'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBlockPreviewRouteImport } from './routes/_authenticated/block-preview'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as BookingActionRescheduleTokenRouteImport } from './routes/booking-action.reschedule.$token'
import { Route as BookingActionActionTokenRouteImport } from './routes/booking-action.$action.$token'
import { Route as ApiSupabaseSplatRouteImport } from './routes/api/supabase/$'
import { Route as ApiReviewsSubmitRouteImport } from './routes/api/reviews/submit'
import { Route as ApiReviewsPeekRouteImport } from './routes/api/reviews/peek'
import { Route as ApiMonitoringClientErrorsRouteImport } from './routes/api/monitoring/client-errors'
import { Route as ApiCronSendRemindersRouteImport } from './routes/api/cron/send-reminders'
import { Route as ApiBookingsSendConfirmationRouteImport } from './routes/api/bookings/send-confirmation'
import { Route as ApiBookingActionsReschedulePeekRouteImport } from './routes/api/booking-actions/reschedule-peek'
import { Route as ApiBookingActionsRescheduleCommitRouteImport } from './routes/api/booking-actions/reschedule-commit'
import { Route as ApiBookingActionsActRouteImport } from './routes/api/booking-actions/act'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPolicyRoute = ReviewPolicyRouteImport.update({
  id: '/review-policy',
  path: '/review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const StaffInviteTokenRoute = StaffInviteTokenRouteImport.update({
  id: '/staff-invite/$token',
  path: '/staff-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioSmsWebhookRoute = ApiTwilioSmsWebhookRouteImport.update({
  id: '/api/twilio-sms-webhook',
  path: '/api/twilio-sms-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStockScanRoute = ApiStockScanRouteImport.update({
  id: '/api/stock-scan',
  path: '/api/stock-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResendWebhookRoute = ApiResendWebhookRouteImport.update({
  id: '/api/resend-webhook',
  path: '/api/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReviewsRoute = ApiPublicReviewsRouteImport.update({
  id: '/api/public-reviews',
  path: '/api/public-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGalleryRoute = ApiPublicGalleryRouteImport.update({
  id: '/api/public-gallery',
  path: '/api/public-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingStaffRoute = ApiPublicBookingStaffRouteImport.update({
  id: '/api/public-booking-staff',
  path: '/api/public-booking-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPageAiSuggestRoute = ApiPageAiSuggestRouteImport.update({
  id: '/api/page-ai-suggest',
  path: '/api/page-ai-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientErrorsRoute = ApiClientErrorsRouteImport.update({
  id: '/api/client-errors',
  path: '/api/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessionalsRoute =
  AuthenticatedProfessionalsRouteImport.update({
    id: '/professionals',
    path: '/professionals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreviewRoute = AuthenticatedPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPageBuilderRoute =
  AuthenticatedPageBuilderRouteImport.update({
    id: '/page-builder',
    path: '/page-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultationsRoute =
  AuthenticatedConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockPreviewRoute =
  AuthenticatedBlockPreviewRouteImport.update({
    id: '/block-preview',
    path: '/block-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BookingActionRescheduleTokenRoute =
  BookingActionRescheduleTokenRouteImport.update({
    id: '/booking-action/reschedule/$token',
    path: '/booking-action/reschedule/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingActionActionTokenRoute =
  BookingActionActionTokenRouteImport.update({
    id: '/booking-action/$action/$token',
    path: '/booking-action/$action/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSupabaseSplatRoute = ApiSupabaseSplatRouteImport.update({
  id: '/api/supabase/$',
  path: '/api/supabase/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsSubmitRoute = ApiReviewsSubmitRouteImport.update({
  id: '/api/reviews/submit',
  path: '/api/reviews/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsPeekRoute = ApiReviewsPeekRouteImport.update({
  id: '/api/reviews/peek',
  path: '/api/reviews/peek',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringClientErrorsRoute =
  ApiMonitoringClientErrorsRouteImport.update({
    id: '/api/monitoring/client-errors',
    path: '/api/monitoring/client-errors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSendRemindersRoute = ApiCronSendRemindersRouteImport.update({
  id: '/api/cron/send-reminders',
  path: '/api/cron/send-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsSendConfirmationRoute =
  ApiBookingsSendConfirmationRouteImport.update({
    id: '/api/bookings/send-confirmation',
    path: '/api/bookings/send-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingActionsReschedulePeekRoute =
  ApiBookingActionsReschedulePeekRouteImport.update({
    id: '/api/booking-actions/reschedule-peek',
    path: '/api/booking-actions/reschedule-peek',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingActionsRescheduleCommitRoute =
  ApiBookingActionsRescheduleCommitRouteImport.update({
    id: '/api/booking-actions/reschedule-commit',
    path: '/api/booking-actions/reschedule-commit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingActionsActRoute = ApiBookingActionsActRouteImport.update({
  id: '/api/booking-actions/act',
  path: '/api/booking-actions/act',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/block-preview': typeof AuthenticatedBlockPreviewRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/consultations': typeof AuthenticatedConsultationsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/page-builder': typeof AuthenticatedPageBuilderRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/professionals': typeof AuthenticatedProfessionalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock': typeof AuthenticatedStockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/page-ai-suggest': typeof ApiPageAiSuggestRoute
  '/api/public-booking-staff': typeof ApiPublicBookingStaffRoute
  '/api/public-gallery': typeof ApiPublicGalleryRoute
  '/api/public-reviews': typeof ApiPublicReviewsRoute
  '/api/resend-webhook': typeof ApiResendWebhookRoute
  '/api/stock-scan': typeof ApiStockScanRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/twilio-sms-webhook': typeof ApiTwilioSmsWebhookRoute
  '/book/$slug': typeof BookSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/review/$token': typeof ReviewTokenRoute
  '/staff-invite/$token': typeof StaffInviteTokenRoute
  '/help/': typeof HelpIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/booking-actions/act': typeof ApiBookingActionsActRoute
  '/api/booking-actions/reschedule-commit': typeof ApiBookingActionsRescheduleCommitRoute
  '/api/booking-actions/reschedule-peek': typeof ApiBookingActionsReschedulePeekRoute
  '/api/bookings/send-confirmation': typeof ApiBookingsSendConfirmationRoute
  '/api/cron/send-reminders': typeof ApiCronSendRemindersRoute
  '/api/monitoring/client-errors': typeof ApiMonitoringClientErrorsRoute
  '/api/reviews/peek': typeof ApiReviewsPeekRoute
  '/api/reviews/submit': typeof ApiReviewsSubmitRoute
  '/api/supabase/$': typeof ApiSupabaseSplatRoute
  '/booking-action/$action/$token': typeof BookingActionActionTokenRoute
  '/booking-action/reschedule/$token': typeof BookingActionRescheduleTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/block-preview': typeof AuthenticatedBlockPreviewRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/consultations': typeof AuthenticatedConsultationsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/page-builder': typeof AuthenticatedPageBuilderRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/professionals': typeof AuthenticatedProfessionalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock': typeof AuthenticatedStockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/page-ai-suggest': typeof ApiPageAiSuggestRoute
  '/api/public-booking-staff': typeof ApiPublicBookingStaffRoute
  '/api/public-gallery': typeof ApiPublicGalleryRoute
  '/api/public-reviews': typeof ApiPublicReviewsRoute
  '/api/resend-webhook': typeof ApiResendWebhookRoute
  '/api/stock-scan': typeof ApiStockScanRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/twilio-sms-webhook': typeof ApiTwilioSmsWebhookRoute
  '/book/$slug': typeof BookSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/review/$token': typeof ReviewTokenRoute
  '/staff-invite/$token': typeof StaffInviteTokenRoute
  '/help': typeof HelpIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/booking-actions/act': typeof ApiBookingActionsActRoute
  '/api/booking-actions/reschedule-commit': typeof ApiBookingActionsRescheduleCommitRoute
  '/api/booking-actions/reschedule-peek': typeof ApiBookingActionsReschedulePeekRoute
  '/api/bookings/send-confirmation': typeof ApiBookingsSendConfirmationRoute
  '/api/cron/send-reminders': typeof ApiCronSendRemindersRoute
  '/api/monitoring/client-errors': typeof ApiMonitoringClientErrorsRoute
  '/api/reviews/peek': typeof ApiReviewsPeekRoute
  '/api/reviews/submit': typeof ApiReviewsSubmitRoute
  '/api/supabase/$': typeof ApiSupabaseSplatRoute
  '/booking-action/$action/$token': typeof BookingActionActionTokenRoute
  '/booking-action/reschedule/$token': typeof BookingActionRescheduleTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/review-policy': typeof ReviewPolicyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/block-preview': typeof AuthenticatedBlockPreviewRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/consultations': typeof AuthenticatedConsultationsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/page-builder': typeof AuthenticatedPageBuilderRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/preview': typeof AuthenticatedPreviewRoute
  '/_authenticated/professionals': typeof AuthenticatedProfessionalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/page-ai-suggest': typeof ApiPageAiSuggestRoute
  '/api/public-booking-staff': typeof ApiPublicBookingStaffRoute
  '/api/public-gallery': typeof ApiPublicGalleryRoute
  '/api/public-reviews': typeof ApiPublicReviewsRoute
  '/api/resend-webhook': typeof ApiResendWebhookRoute
  '/api/stock-scan': typeof ApiStockScanRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/twilio-sms-webhook': typeof ApiTwilioSmsWebhookRoute
  '/book/$slug': typeof BookSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/review/$token': typeof ReviewTokenRoute
  '/staff-invite/$token': typeof StaffInviteTokenRoute
  '/help/': typeof HelpIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/booking-actions/act': typeof ApiBookingActionsActRoute
  '/api/booking-actions/reschedule-commit': typeof ApiBookingActionsRescheduleCommitRoute
  '/api/booking-actions/reschedule-peek': typeof ApiBookingActionsReschedulePeekRoute
  '/api/bookings/send-confirmation': typeof ApiBookingsSendConfirmationRoute
  '/api/cron/send-reminders': typeof ApiCronSendRemindersRoute
  '/api/monitoring/client-errors': typeof ApiMonitoringClientErrorsRoute
  '/api/reviews/peek': typeof ApiReviewsPeekRoute
  '/api/reviews/submit': typeof ApiReviewsSubmitRoute
  '/api/supabase/$': typeof ApiSupabaseSplatRoute
  '/booking-action/$action/$token': typeof BookingActionActionTokenRoute
  '/booking-action/reschedule/$token': typeof BookingActionRescheduleTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookie-policy'
    | '/faq'
    | '/help'
    | '/portal'
    | '/privacy'
    | '/refund-policy'
    | '/review-policy'
    | '/status'
    | '/terms'
    | '/assistant'
    | '/block-preview'
    | '/bookings'
    | '/calendar'
    | '/consultations'
    | '/customers'
    | '/dashboard'
    | '/import'
    | '/onboarding'
    | '/page-builder'
    | '/payments'
    | '/preview'
    | '/professionals'
    | '/reports'
    | '/services'
    | '/settings'
    | '/staff'
    | '/stock'
    | '/api/chat'
    | '/api/client-errors'
    | '/api/health'
    | '/api/page-ai-suggest'
    | '/api/public-booking-staff'
    | '/api/public-gallery'
    | '/api/public-reviews'
    | '/api/resend-webhook'
    | '/api/stock-scan'
    | '/api/stripe-webhook'
    | '/api/twilio-sms-webhook'
    | '/book/$slug'
    | '/help/$slug'
    | '/invite/$token'
    | '/portal/bookings'
    | '/portal/profile'
    | '/review/$token'
    | '/staff-invite/$token'
    | '/help/'
    | '/portal/'
    | '/api/booking-actions/act'
    | '/api/booking-actions/reschedule-commit'
    | '/api/booking-actions/reschedule-peek'
    | '/api/bookings/send-confirmation'
    | '/api/cron/send-reminders'
    | '/api/monitoring/client-errors'
    | '/api/reviews/peek'
    | '/api/reviews/submit'
    | '/api/supabase/$'
    | '/booking-action/$action/$token'
    | '/booking-action/reschedule/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookie-policy'
    | '/faq'
    | '/privacy'
    | '/refund-policy'
    | '/review-policy'
    | '/status'
    | '/terms'
    | '/assistant'
    | '/block-preview'
    | '/bookings'
    | '/calendar'
    | '/consultations'
    | '/customers'
    | '/dashboard'
    | '/import'
    | '/onboarding'
    | '/page-builder'
    | '/payments'
    | '/preview'
    | '/professionals'
    | '/reports'
    | '/services'
    | '/settings'
    | '/staff'
    | '/stock'
    | '/api/chat'
    | '/api/client-errors'
    | '/api/health'
    | '/api/page-ai-suggest'
    | '/api/public-booking-staff'
    | '/api/public-gallery'
    | '/api/public-reviews'
    | '/api/resend-webhook'
    | '/api/stock-scan'
    | '/api/stripe-webhook'
    | '/api/twilio-sms-webhook'
    | '/book/$slug'
    | '/help/$slug'
    | '/invite/$token'
    | '/portal/bookings'
    | '/portal/profile'
    | '/review/$token'
    | '/staff-invite/$token'
    | '/help'
    | '/portal'
    | '/api/booking-actions/act'
    | '/api/booking-actions/reschedule-commit'
    | '/api/booking-actions/reschedule-peek'
    | '/api/bookings/send-confirmation'
    | '/api/cron/send-reminders'
    | '/api/monitoring/client-errors'
    | '/api/reviews/peek'
    | '/api/reviews/submit'
    | '/api/supabase/$'
    | '/booking-action/$action/$token'
    | '/booking-action/reschedule/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookie-policy'
    | '/faq'
    | '/help'
    | '/portal'
    | '/privacy'
    | '/refund-policy'
    | '/review-policy'
    | '/status'
    | '/terms'
    | '/_authenticated/assistant'
    | '/_authenticated/block-preview'
    | '/_authenticated/bookings'
    | '/_authenticated/calendar'
    | '/_authenticated/consultations'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/onboarding'
    | '/_authenticated/page-builder'
    | '/_authenticated/payments'
    | '/_authenticated/preview'
    | '/_authenticated/professionals'
    | '/_authenticated/reports'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/stock'
    | '/api/chat'
    | '/api/client-errors'
    | '/api/health'
    | '/api/page-ai-suggest'
    | '/api/public-booking-staff'
    | '/api/public-gallery'
    | '/api/public-reviews'
    | '/api/resend-webhook'
    | '/api/stock-scan'
    | '/api/stripe-webhook'
    | '/api/twilio-sms-webhook'
    | '/book/$slug'
    | '/help/$slug'
    | '/invite/$token'
    | '/portal/bookings'
    | '/portal/profile'
    | '/review/$token'
    | '/staff-invite/$token'
    | '/help/'
    | '/portal/'
    | '/api/booking-actions/act'
    | '/api/booking-actions/reschedule-commit'
    | '/api/booking-actions/reschedule-peek'
    | '/api/bookings/send-confirmation'
    | '/api/cron/send-reminders'
    | '/api/monitoring/client-errors'
    | '/api/reviews/peek'
    | '/api/reviews/submit'
    | '/api/supabase/$'
    | '/booking-action/$action/$token'
    | '/booking-action/reschedule/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReviewPolicyRoute: typeof ReviewPolicyRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiClientErrorsRoute: typeof ApiClientErrorsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPageAiSuggestRoute: typeof ApiPageAiSuggestRoute
  ApiPublicBookingStaffRoute: typeof ApiPublicBookingStaffRoute
  ApiPublicGalleryRoute: typeof ApiPublicGalleryRoute
  ApiPublicReviewsRoute: typeof ApiPublicReviewsRoute
  ApiResendWebhookRoute: typeof ApiResendWebhookRoute
  ApiStockScanRoute: typeof ApiStockScanRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTwilioSmsWebhookRoute: typeof ApiTwilioSmsWebhookRoute
  BookSlugRoute: typeof BookSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  StaffInviteTokenRoute: typeof StaffInviteTokenRoute
  ApiBookingActionsActRoute: typeof ApiBookingActionsActRoute
  ApiBookingActionsRescheduleCommitRoute: typeof ApiBookingActionsRescheduleCommitRoute
  ApiBookingActionsReschedulePeekRoute: typeof ApiBookingActionsReschedulePeekRoute
  ApiBookingsSendConfirmationRoute: typeof ApiBookingsSendConfirmationRoute
  ApiCronSendRemindersRoute: typeof ApiCronSendRemindersRoute
  ApiMonitoringClientErrorsRoute: typeof ApiMonitoringClientErrorsRoute
  ApiReviewsPeekRoute: typeof ApiReviewsPeekRoute
  ApiReviewsSubmitRoute: typeof ApiReviewsSubmitRoute
  ApiSupabaseSplatRoute: typeof ApiSupabaseSplatRoute
  BookingActionActionTokenRoute: typeof BookingActionActionTokenRoute
  BookingActionRescheduleTokenRoute: typeof BookingActionRescheduleTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-policy': {
      id: '/review-policy'
      path: '/review-policy'
      fullPath: '/review-policy'
      preLoaderRoute: typeof ReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/staff-invite/$token': {
      id: '/staff-invite/$token'
      path: '/staff-invite/$token'
      fullPath: '/staff-invite/$token'
      preLoaderRoute: typeof StaffInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio-sms-webhook': {
      id: '/api/twilio-sms-webhook'
      path: '/api/twilio-sms-webhook'
      fullPath: '/api/twilio-sms-webhook'
      preLoaderRoute: typeof ApiTwilioSmsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stock-scan': {
      id: '/api/stock-scan'
      path: '/api/stock-scan'
      fullPath: '/api/stock-scan'
      preLoaderRoute: typeof ApiStockScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resend-webhook': {
      id: '/api/resend-webhook'
      path: '/api/resend-webhook'
      fullPath: '/api/resend-webhook'
      preLoaderRoute: typeof ApiResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-reviews': {
      id: '/api/public-reviews'
      path: '/api/public-reviews'
      fullPath: '/api/public-reviews'
      preLoaderRoute: typeof ApiPublicReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-gallery': {
      id: '/api/public-gallery'
      path: '/api/public-gallery'
      fullPath: '/api/public-gallery'
      preLoaderRoute: typeof ApiPublicGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-booking-staff': {
      id: '/api/public-booking-staff'
      path: '/api/public-booking-staff'
      fullPath: '/api/public-booking-staff'
      preLoaderRoute: typeof ApiPublicBookingStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/page-ai-suggest': {
      id: '/api/page-ai-suggest'
      path: '/api/page-ai-suggest'
      fullPath: '/api/page-ai-suggest'
      preLoaderRoute: typeof ApiPageAiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-errors': {
      id: '/api/client-errors'
      path: '/api/client-errors'
      fullPath: '/api/client-errors'
      preLoaderRoute: typeof ApiClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professionals': {
      id: '/_authenticated/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof AuthenticatedProfessionalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preview': {
      id: '/_authenticated/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthenticatedPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/page-builder': {
      id: '/_authenticated/page-builder'
      path: '/page-builder'
      fullPath: '/page-builder'
      preLoaderRoute: typeof AuthenticatedPageBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations': {
      id: '/_authenticated/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AuthenticatedConsultationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/block-preview': {
      id: '/_authenticated/block-preview'
      path: '/block-preview'
      fullPath: '/block-preview'
      preLoaderRoute: typeof AuthenticatedBlockPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/booking-action/reschedule/$token': {
      id: '/booking-action/reschedule/$token'
      path: '/booking-action/reschedule/$token'
      fullPath: '/booking-action/reschedule/$token'
      preLoaderRoute: typeof BookingActionRescheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-action/$action/$token': {
      id: '/booking-action/$action/$token'
      path: '/booking-action/$action/$token'
      fullPath: '/booking-action/$action/$token'
      preLoaderRoute: typeof BookingActionActionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase/$': {
      id: '/api/supabase/$'
      path: '/api/supabase/$'
      fullPath: '/api/supabase/$'
      preLoaderRoute: typeof ApiSupabaseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/submit': {
      id: '/api/reviews/submit'
      path: '/api/reviews/submit'
      fullPath: '/api/reviews/submit'
      preLoaderRoute: typeof ApiReviewsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/peek': {
      id: '/api/reviews/peek'
      path: '/api/reviews/peek'
      fullPath: '/api/reviews/peek'
      preLoaderRoute: typeof ApiReviewsPeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring/client-errors': {
      id: '/api/monitoring/client-errors'
      path: '/api/monitoring/client-errors'
      fullPath: '/api/monitoring/client-errors'
      preLoaderRoute: typeof ApiMonitoringClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-reminders': {
      id: '/api/cron/send-reminders'
      path: '/api/cron/send-reminders'
      fullPath: '/api/cron/send-reminders'
      preLoaderRoute: typeof ApiCronSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/send-confirmation': {
      id: '/api/bookings/send-confirmation'
      path: '/api/bookings/send-confirmation'
      fullPath: '/api/bookings/send-confirmation'
      preLoaderRoute: typeof ApiBookingsSendConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-actions/reschedule-peek': {
      id: '/api/booking-actions/reschedule-peek'
      path: '/api/booking-actions/reschedule-peek'
      fullPath: '/api/booking-actions/reschedule-peek'
      preLoaderRoute: typeof ApiBookingActionsReschedulePeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-actions/reschedule-commit': {
      id: '/api/booking-actions/reschedule-commit'
      path: '/api/booking-actions/reschedule-commit'
      fullPath: '/api/booking-actions/reschedule-commit'
      preLoaderRoute: typeof ApiBookingActionsRescheduleCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-actions/act': {
      id: '/api/booking-actions/act'
      path: '/api/booking-actions/act'
      fullPath: '/api/booking-actions/act'
      preLoaderRoute: typeof ApiBookingActionsActRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBlockPreviewRoute: typeof AuthenticatedBlockPreviewRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedConsultationsRoute: typeof AuthenticatedConsultationsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPageBuilderRoute: typeof AuthenticatedPageBuilderRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPreviewRoute: typeof AuthenticatedPreviewRoute
  AuthenticatedProfessionalsRoute: typeof AuthenticatedProfessionalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBlockPreviewRoute: AuthenticatedBlockPreviewRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedConsultationsRoute: AuthenticatedConsultationsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPageBuilderRoute: AuthenticatedPageBuilderRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPreviewRoute: AuthenticatedPreviewRoute,
  AuthenticatedProfessionalsRoute: AuthenticatedProfessionalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface PortalRouteChildren {
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookingsRoute: PortalBookingsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReviewPolicyRoute: ReviewPolicyRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiClientErrorsRoute: ApiClientErrorsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPageAiSuggestRoute: ApiPageAiSuggestRoute,
  ApiPublicBookingStaffRoute: ApiPublicBookingStaffRoute,
  ApiPublicGalleryRoute: ApiPublicGalleryRoute,
  ApiPublicReviewsRoute: ApiPublicReviewsRoute,
  ApiResendWebhookRoute: ApiResendWebhookRoute,
  ApiStockScanRoute: ApiStockScanRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTwilioSmsWebhookRoute: ApiTwilioSmsWebhookRoute,
  BookSlugRoute: BookSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  StaffInviteTokenRoute: StaffInviteTokenRoute,
  ApiBookingActionsActRoute: ApiBookingActionsActRoute,
  ApiBookingActionsRescheduleCommitRoute:
    ApiBookingActionsRescheduleCommitRoute,
  ApiBookingActionsReschedulePeekRoute: ApiBookingActionsReschedulePeekRoute,
  ApiBookingsSendConfirmationRoute: ApiBookingsSendConfirmationRoute,
  ApiCronSendRemindersRoute: ApiCronSendRemindersRoute,
  ApiMonitoringClientErrorsRoute: ApiMonitoringClientErrorsRoute,
  ApiReviewsPeekRoute: ApiReviewsPeekRoute,
  ApiReviewsSubmitRoute: ApiReviewsSubmitRoute,
  ApiSupabaseSplatRoute: ApiSupabaseSplatRoute,
  BookingActionActionTokenRoute: BookingActionActionTokenRoute,
  BookingActionRescheduleTokenRoute: BookingActionRescheduleTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
